#! /bin/sh

killall sxhkd
sxhkd &
setxkbmap pl

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then 
	xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1
fi

picom --config ~/.config/picom.conf &
# ~/.config/polybar/launch.sh & 
feh --bg-fill ~/wallpaper.png

bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI1 -d VI VII VIII IX
bspc config border_width 2
bspc config window_gap 8
bspc config border_radius 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#9DC4B5'

$HOME/.config/polybar/launch.sh
