#! /bin/sh

killall sxhkd
sxhkd &

setxkbmap pl

picom --config ~/.config/picom.conf &
# ~/.config/polybar/launch.sh & 
feh --bg-fill ~/wallpaper.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 10
bspc config border_radius 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#9DC4B5'

$HOME/.config/polybar/launch.sh
