#! /bin/sh

# Kill previous instances of sxhkd
killall sxhkd
sxhkd &
setxkbmap pl

# Automatically change display setup if second monitor is detected
if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then 
	xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate normal --right-of eDP-1
fi

picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/wallpaper.png &
$HOME/.config/polybar/launch.sh main &

bspc monitor eDP-1 -d I II III IV
bspc monitor HDMI-1 -d VI VII VIII
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#9DC4B5'

