#! /bin/sh

# Kill previous instances of sxhkd
killall sxhkd
sxhkd &
setxkbmap pl

# Start compositor, wallpaper and polybar
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/wallpaper.png &
$HOME/.config/polybar/launch.sh main &

# Configure bspwm monitors
bspc monitor HDMI-0 -d I II III IV V VI
# bspc monitor eDP-1 -d VI VII VIII
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#9DC4B5'

